/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.github.richsan

import richsan.KDynaMapper
import kotlin.test.Test
import kotlin.test.assertTrue

data class SimpleObject(val msg : String,
                        val number : Int)


class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val obj =  SimpleObject("this is a test", 42)

        val dynaMap = KDynaMapper.mapToDynamoObjectRequest(obj)

        assert(dynaMap["msg"]?.s() == obj.msg)
        assert(dynaMap["number"]?.n() == obj.number.toString())

        val newObj = KDynaMapper.fromDynamoMapResponse(dynaMap, SimpleObject::class)

        assert(newObj == obj)
    }
}
